name: test-run

on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        rust-toolchain: [nightly]
    env:
      RUSTUP_TOOLCHAIN: ${{ matrix.rust-toolchain }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: rust-src, clippy, rustfmt
          targets: x86_64-unknown-linux-gnu
      - name: Run tests
        run: cargo run

  test-local:
    uses: StarryTest/Top/.github/workflows/test_run.yaml@main
    with:
        my-input: "test-local"

  # test-external:
  #   runs-on: ubuntu-latest
  #   if: github.repository_owner == 'StarryTest'
  #   needs: test
  #   strategy:
  #     fail-fast: false
  #   steps:
  #   - uses: convictional/trigger-workflow-and-wait@v1.6.1
  #     with:
  #       owner: StarryTest
  #       repo: Top
  #       github_token: ${{ secrets.STARRYOS }}
  #       github_user: Azure-stars
  #       workflow_file_name: test_run.yaml
  #       wait_interval: 10
  #       client_payload: '{"commit": "${{ github.sha }}"}'
  #       propagate_failure: true
  #       trigger_workflow: true
  #       wait_workflow: true